project_id = "wonvlwajwhjunccyopvq"

[functions.create-payment]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false